spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: # optional
      database: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/tenet_db?currentSchema=public&options=-c%20TimeZone=UTC
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
  jackson:
    time-zone: Asia/Kolkata
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      group-id: 'credit-consumer'
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        specific.protobuf.value.type: com.simpleAnalytics.protobuf.EventProto$EventCreditConsumptionInfo
    properties:
      schema.registry.url: http://localhost:8081
    bootstrap-servers: localhost:29092